apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dind
  template:
    metadata:
      labels:
        app: dind
    spec:
      containers:
      - name: dind
        image: docker:dind
        securityContext:
          privileged: true
        ports:
        - containerPort: 2375
          protocol: TCP
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
